version: 2

jobs:
  install:
    docker:
      - image: circleci/node:11
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .git
    # Restore local dependencies from cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
    # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm ci
    # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint:
    docker:
      - image: circleci/node:11
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: node ./node_modules/@angular/cli/bin/ng lint

  test:
    docker:
      - image: circleci/node:11-browsers
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: |
          node ./node_modules/@angular/cli/bin/ng test -- --watch=false --progress=false --browsers=ChromeHeadlessCI --code-coverage
          node ./node_modules/@angular/cli/bin/ng e2e -- --protractor-config=./e2e/protractor-ci.conf.js
          cat coverage/index.html | grep '% <\/span>' # display coverage result

  build:
    docker:
      - image: circleci/node:11
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Branch }}-{{ .Revision }}
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: node ./node_modules/@angular/cli/bin/ng build --prod
      - save_cache:
          key: v1-dist-{{ .Environment.CIRCLE_BRANCH }}
          paths:
            - dist

  deploy:
    machine:
      enabled: true
    steps:
      - restore_cache:
          keys:
            - v1-dist-{{ .Environment.CIRCLE_BRANCH }}
      - run:
          name: Deploy over SSH
          command: scp -r dist/galeries-ponthe/* $SSH_USER@$SSH_HOST:/srv/ponthe$([ "${CIRCLE_BRANCH}" == "master" ] || echo "-${CIRCLE_BRANCH}").enpc.org/volumes/static/

workflows:
  version: 2
  main:
    jobs:
      - install
      - build:
          requires:
            - install
